### ISSUE TITLE
直接就崩了啊...

### ISSUE THREAD

**Issue by arnohxr** [zsh065400/QrcodeLib#1]
打开就蹦了，直接报异常：    java.lang.UnsatisfiedLinkError: Couldn't load zbar from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.globex.zhuzhu-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.globex.zhuzhu-2, /vendor/lib, /system/lib]]]: findLibrary returned null。华为荣耀4.4.4系统，三星s6两个试过，都是一样的结果。

**Comment by zsh065400** [comment]
很抱歉，适配6.0时有一个问题没有考虑，现在应该没有问题了，请拉取最新的更新。如有问题请再给我反馈，谢谢

**Comment by zsh065400** [comment]
这个异常是so库的异常，请注意使用时是否有so文件在相应包下。有的AS版本需要特殊设置。
